name: MarisSettings
version: '1.0'
author: Maris
main: com.maris7.settings.MarisSettingsPlugin
api-version: '1.21'
folia-supported: true
depend:
  - packetevents
softdepend:
  - MarisChat
  - MarisAuction
  - MarisTpa
  - MarisCore
  - MarisWorth
  - MarisDuels
  - MarisTeam
  - PlaceholderAPI
commands:
  settings:
    description: Open MarisSettings GUI
    usage: /settings
    aliases: [marissettings, mssettings]
  settingsadmin:
    description: Reload MarisSettings
    usage: /settingsadmin reload
permissions:
  marissettings.use:
    default: true
  marissettings.admin:
    default: op
libraries:
  - com.zaxxer:HikariCP:7.0.2
  - org.xerial:sqlite-jdbc:3.53.0.0
  - com.mysql:mysql-connector-j:9.7.0
